language: cpp

compiler: gcc
env:
  global:
    - COMPILER=g++-4.9
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "X5fQfaSqq7vTJDpIYit0LMHf66kQZDApxVYknDIlKDANTAauJlbE3uck/uRta2xPtOEkjyXEfcxV1pe3FiI9i/EuoYmbYsRsn1uPhK7oMVyxEP1G7DXeaSYPLkN7p3rHPMBSNQQ3TWbAU1n5lqXnkh4fBGSgs74bpKvblCgX35uOsXXUddp8Lw75UVW7fYWPURNU+Ovw5//rX16R96GsD66uHUTXz91CBixMmNLHGdizpNhc/XQPtBV8VZ38B/8pT/3kLdJ8JNTjUGgHR8pYRkadZcaToUeZ/uVW/3gvznUHU/8eioZPhU3eJgk1pKGBeG4ZzejdOb0kick1XkIOjN4Nu0afunWvHOcHFawBPSC3+upFEhj6Q/j/JlKoXaadEkNdnSwwrPbRax7B3RhFhZFhLlVxeOw7I1AvgzCXSeYgbnc0FZe9HxVnZgNvxYLscN7K6yYPiGiMDGZp6JCgAG/iJ/JPR3cXQiIssog7xKXpZt9buh/pQE6bd+duq+F9CO9uhNztSKzWK+hrLf/KiHRSXrGNi4tsIKa68xJ6BKXs2tHMWmL1MIaPl8Z8mOGbomVRdZKlfPb54c0QIFSydYcWD/JYw73voq5/ja+jBRDC/+ndQNgrAGBwsxt1F8dViDzDdhhdEwfPt3oVKapBimQ9wchA7wUmBaPHinyD0Os="

sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - valgrind
      - owfs
  coverity_scan:
    project:
      name: "FragJage/xPLOwfs"
      description: "xPL daemon to communicate with one wire device"
    notification_email: inscrip.jage@free.fr
    build_command_prepend: "cov-configure --comptype g++ --compiler $(which $COMPILER) && cmake . -G'Unix Makefiles' -DCMAKE_CXX_COMPILER=$(which $COMPILER)"
    build_command: "make"
    branch_pattern: coverity_branch
    
install:
  - pip install --user git+git://github.com/eddyxu/cpp-coveralls.git
  - content=$(curl -L 127.0.0.1:2121)
  - echo $content
  - /etc/init.d/owserver stop
  - /etc/init.d/owhttpd stop
  - cat /etc/owfs.conf
  - sed -r "s/^server:.*$/server:FAKE=DS18S20,DS18S20,DS2405/g" /etc/owfs.conf
  - cat /etc/owfs.conf
  - /etc/init.d/owserver start
  - /etc/init.d/owhttpd start
  - content=$(curl -L 127.0.0.1:2121)
  - echo $content

script:
  - if [ "$COVERITY_SCAN_BRANCH" != 1 ]; then cmake . -G"Unix Makefiles" -DCMAKE_CXX_COMPILER=$(which $COMPILER); fi
  - if [ "$COVERITY_SCAN_BRANCH" != 1 ]; then make; fi
  - if [ "$COVERITY_SCAN_BRANCH" != 1 ]; then ./test/bin/unittest; fi

after_success:
  - if [ "$COVERITY_SCAN_BRANCH" != 1 ]; then valgrind --error-exitcode=1 --leak-check=full ./test/bin/unittest; fi
  - if [ "$COVERITY_SCAN_BRANCH" != 1 ]; then coveralls --include src --gcov-options '\-lp' --gcov 'gcov-4.9'; fi
